### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by ds82** [lab2023/hierapolis#47]
> $ bundle update
> [...]
> Your bundle is updated!
> $ compass watch
> 
> NoMethodError on line ["264"] of /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/inheritance.rb: compass_config
> Run with --trace to see the full backtrace

Am I doing it wrong?
I'm on Mac OSX 10.8.5.

**Comment by onurozgurozkan** [comment]
Could you please `$ compass watch --trace` and give us more information? Regards.

**Comment by ds82** [comment]
sure.

```
NoMethodError on line ["264"] of /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/inheritance.rb: compass_config
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/inheritance.rb:262:in `method_missing'
  /Users/dsaenger/code/web/hierapolis/config.rb:16:in `get_binding'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/serialization.rb:24:in `eval'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/serialization.rb:24:in `parse_string'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/serialization.rb:15:in `block in _parse'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/serialization.rb:14:in `open'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/serialization.rb:14:in `_parse'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/file_data.rb:7:in `block in new_from_file'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/inheritance.rb:204:in `with_defaults'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/file_data.rb:6:in `new_from_file'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/helpers.rb:42:in `configuration_for'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/configuration/helpers.rb:97:in `add_project_configuration'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/commands/project_base.rb:37:in `add_project_configuration'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/commands/project_base.rb:25:in `configure!'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/commands/project_base.rb:15:in `initialize'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/commands/update_project.rb:37:in `initialize'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/exec/sub_command_ui.rb:42:in `new'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/exec/sub_command_ui.rb:42:in `perform!'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/bin/compass:30:in `block in <top (required)>'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/bin/compass:44:in `call'
  /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/compass-0.12.6/bin/compass:44:in `<top (required)>'
  /usr/local/Cellar/ruby/2.0.0-p0/bin//compass:23:in `load'
  /usr/local/Cellar/ruby/2.0.0-p0/bin//compass:23:in `<main>'
```

thanks for looking into it!

**Comment by tayfunoziserikan** [comment]
Did you run? `$ bundle install`
Are you sure of all the GEMs installed?

**Comment by ds82** [comment]
Yes I did (just did it again just to be sure).
How can I be sure that all gems are installed? I thought `bundle install` takes care of that.

**Comment by tayfunoziserikan** [comment]
Please run `$ compass -v` command in project path and would you please show the output?

**Comment by onurozgurozkan** [comment]
What about  `bundle exec middleman` ? Can you run middleman correctly at http://0.0.0.0:4567/ ?

**Comment by ds82** [comment]
```
$ compass -v
Compass 0.12.6 (Alnilam)
Copyright (c) 2008-2014 Chris Eppstein
Released under the MIT License.
Compass is charityware.
Please make a tax deductable donation for a worthy cause: http://umdf.org/compass
```

```
$ bundle exec middleman
== The Middleman is loading
== Locales: en (Default en)
== LiveReload is waiting for a browser to connect
== The Middleman is standing watch at http://0.0.0.0:4567
== Inspect your site configuration at http://0.0.0.0:4567/__middleman/
```

Looks fine, but when I open localhost:4567 I get this:

```
Error compiling CSS asset

NoMethodError: undefined method `font_path'  for nil:NilClass
  (in [...] application.css.sass)

/usr/.../sprockets/sass/functions.rb:98
```

**Comment by adamdilek** [comment]
@ds82 Maybe this can help you https://github.com/middleman/middleman/issues/1265

**Comment by ds82** [comment]
@muhammetdilek That helped indeed, thank you!. I added this line to the Gemfile:

```
gem 'middleman-sprockets', '3.3.2'
```

I opened a pull request (https://github.com/lab2023/hierapolis/pull/48) if you guys want to take that change into your repo. 

Still, the issue with `compass watch` remains :/
