### ISSUE TITLE
Middleman? I don't understand it 

### ISSUE THREAD

**Issue by khatnuoc994** [lab2023/hierapolis#53]
i was clone in github, but i can't understand next step are "Bundle install" and "Middleman" to get css and html code. Can you give me some ideas?

**Comment by tayfunoziserikan** [comment]
Hi, 

This project uses [Middleman](http://middlemanapp.com/) You can find more information about middleman here: http://middlemanapp.com/basics/getting-started/

If you need css and js files you can use `middleman build` command.

**Comment by 254347458** [comment]
can Middleman run in Windows?

**Comment by coskuntekin** [comment]
If you have ruby (gem system) on windows, yes you can. But recommend on linux or osx

**Comment by ghost** [comment]
Hey there,
i cant run middleman on windows. Istnt there any possibility to get the html and css files or can someone build it for me please?

**Comment by ghost** [comment]
please!

**Comment by adamdilek** [comment]
Hi @Nico2705 This is only html https://github.com/lab2023/hierapolis/tree/gh-pages

**Comment by coskuntekin** [comment]
Thank you @muhammetdilek (+1) What we want. Now "hierapolis" more useful

**Comment by azzynugraha** [comment]
@tayfunoziserikan I've run the command "middleman build" but there are error : 

![Error Middleman](http://i60.tinypic.com/ouwemt.png)

can you help me to solve this problem?

**Comment by adamdilek** [comment]
@azzynugraha use `bundle exec middleman build`

**Comment by azzynugraha** [comment]
@muhammetdilek i've run the command and still get error : 

```
C:\Users\bintang\Documents\GitHub\hierapolis-develop>bundle exec middleman build

DL is deprecated, please use Fiddle
DL is deprecated, please use Fiddle
C:/Ruby21/lib/ruby/2.1.0/uri/common.rb:176:in `split': bad URI(is not URI?): ass
ets%5Cimages%5CC:%5CUsers%5Cbintang%5CDocuments%5CGitHub%5Chierapolis-develop%5C
source%5Cassets%5Cimages%5Capple-touch-icon-114x114-precomposed.png (URI::Invali
dURIError)
        from C:/Ruby21/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
        from C:/Ruby21/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-test-0.6.3/lib/rack/test.rb
:193:in `env_for'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-test-0.6.3/lib/rack/test.rb
:57:in `get'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-more/extensions/asset_hash.rb:47:in `manipulate_single_resource'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-more/extensions/asset_hash.rb:38:in `each'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-more/extensions/asset_hash.rb:38:in `manipulate_resource_list'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-core/sitemap/store.rb:215:in `block (2 levels) in ensure_resource_list_update
d!'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-core/sitemap/store.rb:214:in `each'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-core/sitemap/store.rb:214:in `reduce'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-core/sitemap/store.rb:214:in `block in ensure_resource_list_updated!'
        from C:/Ruby21/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-core/sitemap/store.rb:208:in `ensure_resource_list_updated!'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-core/sitemap/extensions/on_disk.rb:31:in `block in initialize'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.13/lib/uber/options.rb:
80:in `instance_exec'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.13/lib/uber/options.rb:
80:in `proc!'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.13/lib/uber/options.rb:
69:in `evaluate_for'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.13/lib/uber/options.rb:
60:in `evaluate'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.0/lib/hooks/hook.rb:53
:in `execute_callback'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.0/lib/hooks/hook.rb:40
:in `block in run'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39
:in `each'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39
:in `inject'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39
:in `run'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.0/lib/hooks.rb:55:in `
run_hook_for'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.0/lib/hooks/instance_h
ooks.rb:6:in `run_hook'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-core/core_extensions/request.rb:50:in `inst'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-core/cli/build.rb:95:in `shared_instance'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-core/cli/build.rb:62:in `build'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:
27:in `run'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.
rb:126:in `invoke_command'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `
dispatch'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440
:in `start'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-core/cli.rb:72:in `method_missing'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:
29:in `run'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:
126:in `run'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.
rb:126:in `invoke_command'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `
dispatch'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440
:in `start'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/lib/middlem
an-core/cli.rb:20:in `start'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.5/bin/middlem
an:18:in `<top (required)>'
        from C:/Ruby21/bin/middleman:23:in `load'
        from C:/Ruby21/bin/middleman:23:in `<main>'
```

**Comment by AIMAGU** [comment]
Thank you @muhammetdilek (+1) What we want. Now "hierapolis" more useful :)

**Comment by MrHamel** [comment]
I wish this theme was available without relying on a language, let alone a crappy ruby framework.

**Comment by abdulmanan7** [comment]
i spend 4 hours ,by understanding Ruby ,Middleman ,then i setup Ruby then run some commands which didnt work ,
finally i get https://github.com/lab2023/hierapolis/tree/gh-pages path !!!

**Comment by atxkm** [comment]
Thanks @muhammet (+1) https://github.com/lab2023/hierapolis/tree/gh-pages
